### ISSUE TITLE
Defining aliases breaks the build

### ISSUE THREAD

**Issue by Martin-Narvar** [emmeowzing/dynamic-continuation-orb#105]
My .circleci/config.yml contains

```yaml
version: 2.1

setup: true

orbs:
  dynamic: bjd2385/dynamic-continuation@3.7.1

workflows:
  generate-config:
    jobs:
      - dynamic/continue:
          name: Generate configs
          context: orb-publishing
          default-branch: master
          modules: |
            /java
            /typescript
            /golang
```

I created corresponding `java.yml`, `golang.yml` and `typescript.yml` files, and the orb does merge them correctly.

However my `java.yaml` contains aliases of the form
```yaml
aliases:
  - &defaults
    docker:
      - image: $DOCKER_REPO/alpine-oraclejdk8:3.11-202-master
    working_directory: ~/soil-core
```

That are uses elsewhere in the script like this:
```yaml
jobs:
  build_java:
    <<: *defaults
    steps:
      - checkout
```

During the merge, validation fails with
```
Error: config compilation contains errors: config compilation contains errors:
        - Unable to parse YAML
        - found undefined alias defaults
        -  in 'string', line 19, column 9:
        -         <<: *defaults
        -             ^
```

I think this is because this dynamic continuation orb moves all of the aliases to the end of the script.
