### ISSUE TITLE
update to use 'main' instead of master?

### ISSUE THREAD

**Issue by szeitlin** [emmeowzing/dynamic-continuation-orb#89]
The filter step is able to detect my modules (yay!) but I'm getting `fatal: ambiguous argument 'master': unknown revision or path not in the working tree.`, I think because modern repos all use `main` instead of `master` ? Not sure if this is in your code or CircleCI's, so feel free to tell me to go make a ticket there instead (or in addition).

**Comment by emmeowzing** [comment]
Hello @szeitlin , yes this is defaulted to `master`. I can update it in the next release to `main`. You can fix this by specifying the default branch, such as

```yaml
setup: true

orbs:
  dynamic: bjd2385/dynamic-continuation@<version>

workflows:
  on-commit:
    jobs:
      - dynamic/continue:
          context: circleci
          default-branch: main
```
